# Generated by Django 3.2.7 on 2021-12-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('net_ipmi', models.CharField(max_length=15)),
                ('net_164', models.CharField(max_length=15)),
                ('net_162', models.CharField(max_length=15)),
                ('net_dmz', models.CharField(max_length=15)),
                ('net_1080', models.CharField(max_length=15)),
                ('net_1090', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('ncpu', models.IntegerField(default=0)),
                ('mem', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ncpu', models.IntegerField(default=0)),
                ('mem', models.IntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostapp.host')),
            ],
        ),
    ]
