# Generated by Django 3.2.7 on 2021-12-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='modelo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ncpu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_1080',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_1090',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_162',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_164',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_dmz',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_ipmi',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='mem',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='ncpu',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
