# Generated by Django 3.2.7 on 2021-12-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0002_auto_20211217_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='net_ipmi',
            new_name='net_mgmt',
        ),
    ]
