# Generated by Django 3.2.7 on 2021-12-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0003_rename_net_ipmi_host_net_mgmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='host',
            name='modelo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='ncpu',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_1080',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_1090',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_162',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_164',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_dmz',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_mgmt',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vm',
            name='mem',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='vm',
            name='ncpu',
            field=models.IntegerField(default=None),
        ),
    ]
