# Generated by Django 3.2.7 on 2021-12-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0004_auto_20211217_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='ncpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_1080',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_1090',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_162',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_164',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_dmz',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='net_mgmt',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vm',
            name='mem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='ncpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
